feat: add postgres database deploy workflow
bcgov/nr-spar-backend pull request #12
Opened 2022-12-29 20:43 UTC by RMCampos

# Description

Add image configuration, build steps and deploy workflows to have a postgres running every time a new pull request is open. 

Fixes [FSADT2-93](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT2-93)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

This was tested using other Pull Requests.

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have already been accepted and merged

## Further comments

2022-12-29 21:35 UTC, DerekRoberts approved these changes
Good work!  :)

2022-12-29 21:37 UTC, paulushcgcj requested changes
Pay attention to the compose file, as you're pushing images to github, and unless you are sure that who's running it got it's environment properly configured, or change it to include the github domain.

Also, the DatabaseDockerfile can be moved to a folder and the name can be changed to Dockerfile again.

2022-12-29 21:37 UTC, paulushcgcj commented on pom.xml
>  			<groupId>com.h2database</groupId>
why do you still have H2 database? If it's for testing purposes, you should scope it as test.

2022-12-29 21:37 UTC, paulushcgcj commented on pom.xml
> +			<version>42.5.1</version>
You can get over without setting up the version, as spring controls driver versions.

2022-12-30 11:28 UTC, RMCampos commented
@paulushcgcj thanks for the docker-compose file review. it was wrong indeed.

2022-12-30 16:55 UTC, paulushcgcj approved these changes

2022-12-30 16:58 UTC, merged