feat:create smp mix entities
bcgov/nr-spar-backend pull request #87
Opened 2023-03-24 14:26 UTC by lucasbuenoencora

# Description

Implementation of the SMPMix Entities: `SmpMix`, `SmpMixGeneticQuality` and `SeedlotParentTreeSmpMix`.

Implements [FSADT2-505](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT2-505)

## Type of change

- [X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- [X] Unit tests for JPA mapping

## Checklist

- [X] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have already been accepted and merged

## Further comments

2023-03-24 20:25 UTC, annibalsilva requested changes

2023-03-24 20:25 UTC, annibalsilva commented on backend/src/main/java/ca/bc/gov/backendstartapi/entity/SmpMixGeneticQuality.java
> +  public Boolean estimatedIndicator;
Optional: we could drop the "Indicator" part of the property name and go with just *estimated* or *qualityValueEstimated*, for instance.

2023-03-24 20:25 UTC, annibalsilva commented on backend/src/test/java/ca/bc/gov/backendstartapi/jpa/SeedlotParentTreeSmpMixJpaTest.java
> +    seedlotParentTreeSmpMix.setGeneticQualityValue(new BigDecimal(10));
*geneticQualityValue* has already been set in the constructor, so this line is redundant.

2023-03-27 14:42 UTC, lucasbuenoencora commented on backend/src/main/java/ca/bc/gov/backendstartapi/entity/SmpMix.java
> +  // endregion
I've talked with @thiagosanchezenc about this and he said that is a valid case for the user to insert a tree that is not in the orchard, therefore, not in the `seedlot_parent_tree`. So either `smp_mix` and `smp_mix_gen_qlty` may have trees that are outside the orchard

2023-03-27 19:34 UTC, annibalsilva commented on backend/src/main/java/ca/bc/gov/backendstartapi/entity/SmpMix.java
> +  private Integer parentTreeId;
It's better to use the primitive (not nullable) `int` instead of the `Integer` in the field `amountOfMaterial` as well.

2023-03-27 19:35 UTC, annibalsilva requested changes
One of the non-nullable fields still uses a wrapper class (i.e. `Integer`).

2023-03-28 14:34 UTC, merged